import mintjulep from "../image/MintJulep.png";
import godfather from "../image/GodFather.png";
import jackcoke from "../image/JackCoke.png";
import bluehawaii from "../image/BlueHawaii.png";
import mojito from "../image/Mojito.png";
import pinacolada from "../image/pinacolada.png";
import whiskeysour from "../image/WhiskeySour.png";
import wildflower from "../image/WildFlower.png";
import amarettosour from "../image/amarettosour.png";
import sexymild from "../image/sexymild.png";
import kahluamlik from "../image/kahluamlik.png";
import bluesapphire from "../image/bluesapphire.png";
import cosmopolitan from "../image/cosmopolitan.png";
import midorisour from "../image/midorisour.png";
import orgasm from "../image/orgasm.png";
import shirleytemple from "../image/shirleytemple.png";
import dohwa from "../image/dohwa.png";
import bacardi from "../image/Bacardi.png";
import cloverclub from "../image/CloverClub.png";
import daiquiri from "../image/Daiquiri.png";
import french75 from "../image/French75.png";
import ink from "../image/Ink.png";
import japaneseslipper from "../image/JapaneseSlipper.png";
import moscowmule from "../image/MoscowMule.png";
import newyorksour from "../image/NewyorkSour.png";
import oldfashioned from "../image/OldFashioned.png";
import gimlet from "../image/Gimlet.png";
import frenchgimlet from "../image/FrenchGimlet.png";
import scotchjamsour from "../image/ScotchJamSour.png";
import tomcollins from "../image/TomCollins.png";
import traditionalelderfashioned from "../image/TraditionalElderfashioned.png";
import hugospritz from "../image/HugoSpritz.png";
import espressomartini from "../image/EspressoMartini.png";

export const recipes = [
  {
    id: "mintjulep",

    name: "Mint Juelp",
    ingredients: [
      "2 oz Bourbon",
      "8 Mint Leaves",
      "1 Mint Sprig",
      "1/2 oz Simple Syrup",
    ],
    details:
      "Muddle the mint leaves and simple syrup in the bottom of a rocks glass or julep cup. Be brief and gentle; abrasive muddling will turn the mint bitter. Add crushed ice and bourbon to the glass, stirring until the glass frosts. Top with more ice, and serve with a straw and mint sprig to tickle your nose.",
    image: mintjulep,
    backgroundcolor: "#819651",
    fontcolor: "rgb(241, 255, 225)",
    cup: "julep",
    IsShow: true,
  },
  {
    id: "godfather",
    name: "God Father",
    ingredients: ["1 1/8 oz Scotch", "1 1/8 oz Disaronno"],
    details:
      "Pour all ingredients into old fashioned glass filled with ice cubes. Stir gently.",
    image: godfather,
    backgroundcolor: "#c0713f",
    fontcolor: "rgb(255, 213, 135)",
    cup: "ontherock",
    IsShow: true,
  },
  {
    id: "jackcoke",
    name: "Jack Coke",
    ingredients: ["1 1/2 oz Jack Daniel's", "1 Coke"],
    details: "",
    image: jackcoke,
    backgroundcolor: "#69392f",
    fontcolor: "rgb(232, 201, 201)",
    cup: "highball",
    IsShow: false,
  },
  {
    id: "bluehawaii",
    name: "Blue Hawaii",
    ingredients: [
      "1 1/2 oz White Rum",
      "1 oz Blue Curaço",
      "1 oz Sweet & sour Mix",
      "4 oz Pineapple Juice",
    ],
    details: "",
    image: bluehawaii,
    backgroundcolor: "#4d91de",
    fontcolor: "rgb(126, 201, 255)",
    cup: "hurricane",
    IsShow: false,
  },
  {
    id: "mojito",
    name: "Mojito",
    ingredients: [
      "1 1/3 oz White Rum",
      "1 oz Fresh Lime Juice",
      "6 Mint Sprigs",
      "2 Tsp White Sugar",
      "Soda Water",
    ],
    details:
      "Muddle mint sprigs with sugar and lime juice. Add splash of soda water and fill glass with cracked ice. Pour rum and top with soda water. Garnish with sprig of mint leaves and lime slice. Serve with straw.",
    image: mojito,
    backgroundcolor: "#819651",
    fontcolor: "rgb(241, 255, 225)",
    cup: "highball",
    IsShow: false,
  },
  {
    id: "pinacolada",
    name: "Piña Colada",
    ingredients: [
      "1 oz White Rum",
      "2 oz Pineapple Juice",
      "3 oz Piña colada mix",
    ],
    details:
      "Blend all the ingredients with ice in an electric blender, pour into a large goblet or Hurricane glass and serve with straw. Garnish with a slice of pineapple or with a cocktail cherry.",
    image: pinacolada,
    backgroundcolor: "#e6ddcb",
    fontcolor: "rgb(148, 148, 61)",
    cup: "hurricane",
    IsShow: false,
  },
  {
    id: "whiskeysour",
    name: "Whiskey Sour",
    ingredients: [
      "2 oz Bourbon",
      "3/4 oz Lemon Juice",
      "3/4 oz Simple Syrup",
      "1 Egg White",
    ],
    details:
      "Add the bourbon, fresh squeezed lemon juice, simple syrup, and egg white to the shaker. Shake first without ice (dry shake) and then shake again with ice. Strain into a rocks glass with ice. If available, double strain through a fine-mesh strainer. Garnish with a lemon peel.",
    image: whiskeysour,
    backgroundcolor: "#d6be50",
    fontcolor: "rgb(245, 255, 180)",
    cup: "martini",
    IsShow: true,
  },
  {
    id: "wildflower",
    name: "Wild Flower",
    ingredients: [
      "1 oz Bourbon",
      "1/2 oz Peach Tree",
      "1/2 oz disaronno",
      "1/2 oz Lime Juice",
    ],
    details: "",
    image: wildflower,
    backgroundcolor: "#fc9a6d",
    fontcolor: "rgb(250, 201, 110)",
    cup: "ontherock",
    IsShow: false,
  },
  {
    id: "amarettosour",
    name: "Amaretto Sour",
    ingredients: [
      "2 oz Amaretto",
      "3/4 oz Lemon Juice",
      "1/4 oz Simple Syrup",
      "1 Egg White",
    ],
    details: "Dry shaking then ice shaking",
    image: amarettosour,
    backgroundcolor: "#d66b29",
    fontcolor: "rgb(241, 255, 225)",
    cup: "coupe",
    IsShow: true,
  },
  {
    id: "sexymild",
    name: "Sexy Mild",
    ingredients: [
      "1 oz Blue Curaço",
      "3 oz Piña colada mix",
      "3 oz Milk",
      "1 oz Sweet & Sour Mix",
    ],
    details: "",
    image: sexymild,
    backgroundcolor: "#a7c5bd",
    fontcolor: "aliceblue",
    cup: "snifter",
    IsShow: false,
  },
  {
    id: "kahluamilk",
    name: "Kahlua Milk",
    ingredients: [
      "1 oz Kahlua",
      "1 oz Milk",
      "make mlik foam",
      "1/2 oz Kahlua",
      "2 oz Milk",
    ],
    details: "",
    image: kahluamlik,
    backgroundcolor: "#814118",
    fontcolor: "#ffffff",
    cup: "ontherock",
    IsShow: false,
  },
  {
    id: "bluesapphire",
    name: "Blue Sapphire",
    ingredients: [
      "1/2 oz Peach Tree",
      "1/2 oz Malibu",
      "1/2 oz Blue Curaço",
      "1/2 oz Sweet & Sour Mix",
      "Sprite fill",
    ],
    details: "",
    image: bluesapphire,
    backgroundcolor: "#416062",
    fontcolor: "#ffffff",
    cup: "flute",
    IsShow: false,
  },
  {
    id: "cosmopolitan",
    name: "Cosmopolitan",
    ingredients: [
      "1 1/3 oz Citron Vodka",
      "1/2 oz Triple sec",
      "1/2 oz Lime Juice",
      "1 oz CranBerry Juice",
    ],
    details: "",
    image: cosmopolitan,
    backgroundcolor: "#cc343f",
    fontcolor: "#ffffff",
    cup: "martini",
    IsShow: false,
  },
  {
    id: "midorisour",
    name: "Midori Sour",
    ingredients: [
      "1 oz Midori",
      "1 oz Sweet & Sour Mix",
      "2/3 oz Lime Juice",
      "Sprite fill",
      "or",
      "2 oz Midori",
      "1 oz Lime Juice",
      "1 egg white",
    ],
    details: "",
    image: midorisour,
    backgroundcolor: "#4c574e",
    fontcolor: "#ffffff",
    cup: "highball",
    IsShow: false,
  },
  {
    id: "orgasm",
    name: "Orgasm",
    ingredients: ["1/2 oz Baileys", "1/2 oz Kahlua", "1/2 oz Disaronno"],
    details: "",
    image: orgasm,
    backgroundcolor: "#bbb292",
    fontcolor: "#515151",
    cup: "coupe",
    IsShow: false,
  },
  {
    id: "dohwa",
    name: "Dohwa (도화)",
    ingredients: [
      "1 oz Peach Tree",
      "2/3 oz Triple Sec",
      "1 1/2 oz Applce Juice",
      "1/3 oz Lemon Juice",
      "1/3 oz Lime Juice",
      "2 Tsp Grenadin Syrup",
      "Sparkling Water fill",
      "Mint top",
    ],
    details: "",
    image: dohwa,
    backgroundcolor: "#e4ddcb",
    fontcolor: "#515151",
    cup: "coupe",
    IsShow: false,
  },
  {
    id: "shirleytemple",
    name: "Shirley Temple",
    ingredients: [
      "1/2 oz Grenadind Syrup",
      "1/3 oz Lime Juice",
      "Ginger Ale fill",
    ],
    details: "",
    image: shirleytemple,
    backgroundcolor: "#ab526b",
    fontcolor: "white",
    cup: "highball",
    IsShow: true,
  },
  {
    id: "newyorksour",
    name: "NewYork Sour",
    ingredients: [
      "2 oz Bourbon",
      "1 oz Lemon Juice",
      "3/4 oz Simple Syrup",
      "Red wine top fill",
    ],
    details: "",
    image: newyorksour,
    backgroundcolor: "#DEAB2C",
    fontcolor: "#515151",
    cup: "ontherock",
    IsShow: true,
  },
  {
    id: "Gimlet",
    name: "Gimlet",
    ingredients: ["1 1/2 oz Gin", "1/3 oz Simple Syrup", "3/4 oz Lime Juice"],
    details: "",
    image: gimlet,
    backgroundcolor: "#E8D84C",
    fontcolor: "#515151",
    cup: "coupe",
    IsShow: true,
  },
  {
    id: "FrenchGimlet",
    name: "French Gimlet",
    ingredients: ["2 oz Gin", "1 oz St. Germain", "1/2 Lime Juice"],
    details: "",
    image: frenchgimlet,
    backgroundcolor: "#F5EE90",
    fontcolor: "#515151",
    cup: "coupe",
    IsShow: true,
  },
  {
    id: "Hugospritz",
    name: "Hugo Spritz",
    ingredients: [
      "1 1/2 oz St. Germain",
      "4 oz Prosecco or white wine",
      "2 oz Soda water or Sprite",
      "8 mint leaves",
    ],
    details: "",
    image: hugospritz,
    backgroundcolor: "#EBCF78",
    fontcolor: "#515151",
    cup: "snifter",
    IsShow: false,
  },
  {
    id: "JapaneseSlipper",
    name: "Japanese Slipper",
    ingredients: [
      "1 oz Midori",
      "1 oz Triple sec",
      "1/2 Lemon Juice",
      "1 Maraschino Cherry",
    ],
    details: "",
    image: japaneseslipper,
    backgroundcolor: "#8DA26E",
    fontcolor: "white",
    cup: "martini",
    IsShow: false,
  },
  {
    id: "TraditionalElderfashioned",
    name: "Traditional Elderfashioned",
    ingredients: [
      "1 2/3 oz Scotch",
      "2/3 oz St. Germain",
      "2 Dash Angostura Bitter",
    ],
    details: "",
    image: traditionalelderfashioned,
    backgroundcolor: "#BE4B38",
    fontcolor: "white",
    cup: "ontherock",
    IsShow: true,
  },
  {
    id: "EspressoMartini",
    name: "Espresso Martini",
    ingredients: [
      "2 oz Vodka",
      "1 oz Espresso",
      "1/2 oz Khaluah",
      "1/2 oz Simple Syrup",
      "3 Whole Coffee Bean",
    ],
    details: "",
    image: espressomartini,
    backgroundcolor: "#762011",
    fontcolor: "white",
    cup: "coupe",
    IsShow: false,
  },
  {
    id: "MoscowMule",
    name: "Moscolw Mule",
    ingredients: ["1 1/2 oz Vodka", "4 oz Ginger Beer", "1/8 oz Lime Juice"],
    details: "",
    backgroundcolor: "#263326",
    fontcolor: "white",
    image: moscowmule,
    cup: "julep",
    IsShow: false,
  },
  {
    id: "Daiquiri",
    name: "Daiquiri",
    ingredients: ["1 1/2 oz Rum", "3/4 oz Lime Juice", "1/2 oz Simple Syrup"],
    details: "",
    backgroundcolor: "#8DA26E",
    fontcolor: "white",
    image: daiquiri,
    cup: "coupe",
    IsShow: false,
  },
  {
    id: "TomCollins",
    name: "Tom Collins",
    ingredients: [
      "2 oz Gin",
      "3/4 oz Simple Syrup",
      "3/4 Lemon Juice",
      "Soda Fill",
    ],
    details: "",
    backgroundcolor: "#E8D84C",
    fontcolor: "#515151",
    image: tomcollins,
    cup: "highball",
    IsShow: true,
  },
  {
    id: "French75",
    name: "French 75",
    ingredients: [
      "1 1/2 oz Gin",
      "3/4 oz Lemon Juice",
      "1/2 oz Simple Syrup",
      "Dry Champagne",
    ],
    details: "",
    backgroundcolor: "#B2C4BC",
    fontcolor: "#515151",
    image: french75,
    cup: "flute",
    IsShow: false,
  },
  {
    id: "CloverClub",
    name: "Clover Club",
    ingredients: [
      "1 1/2 oz Gin",
      "1/2 oz RaspBerry Syrup",
      "1/2 oz Lemon Juice",
      "Egg white",
    ],
    details: "",
    backgroundcolor: "#AB526B",
    fontcolor: "white",
    image: cloverclub,
    cup: "martini",
    IsShow: true,
  },
  {
    id: "Ink",
    name: "Ink",
    ingredients: [
      "1 1/4 oz Gin",
      "1/2 oz Blue Curaço",
      "1/2 oz Peach Tree",
      "2 oz Crenberry Juice",
      "Orange Peel",
    ],
    details: "",
    backgroundcolor: "#524656",
    fontcolor: "white",
    image: ink,
    cup: "",
    IsShow: false,
  },
  {
    id: "ScotchJamSour",
    name: "Scotch Jam Sour",
    ingredients: [
      "1 1/2 oz Scotch",
      "2/3 oz Lemon Juice",
      "1/3 oz Simple Syrup",
      "2 Tsp Strawberry Jam",
      "1 dash Bitter",
    ],
    details: "",
    image: scotchjamsour,
    backgroundcolor: "#EB7B5A",
    fontcolor: "white",
    cup: "ontherock",
    IsShow: true,
  },
  {
    id: "OldFashioned",
    name: "Old Fashioned",
    ingredients: [
      "2 oz Bourbon",
      "3 gram Sugar",
      "3 dash Angostura Bitter",
      "Orange Peel",
      "Maraschino Cherry",
    ],
    details: "",
    backgroundcolor: "#B0420B",
    fontcolor: "white",
    image: oldfashioned,
    cup: "ontherock",
    IsShow: true,
  },
  {
    id: "Bacardi",
    name: "Bacardi",
    ingredients: [
      "2 oz Bacardi Rum",
      "1/4 oz Lime Juice",
      "1/4 oz Grenadine Syrup",
      "1 Tsp Simple Syrup",
    ],
    details: "",
    backgroundcolor: "#EB7B5A",
    fontcolor: "white",
    image: bacardi,
    cup: "martini",
    IsShow: false,
  },
];
